#!/bin/bash
#
# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Find dx.jar from dx in the android dev tree
prog=`which dx`
progdir=`dirname "${prog}"`

# Find dx.jar from dx in the android dev tree
prog=`which dx`
progdir=`dirname "${prog}"`

javac testdata/*.java
dx --dex --output=testdata/A.dex testdata/A.class
dx --dex --output=testdata/B.dex testdata/B.class
jar cfM resources.jar testdata/*.dex

vogar --classpath resources.jar \
  --classpath $progdir/../framework/dx.jar \
  com/android/dx/merge/MergeConflictTest.java > unit-out.txt

if [ "$?" = "0" ]; then
    echo "Yay!"
else
    cat unit-out.txt
fi


