#!/bin/bash
#
# Copyright (C) 2007 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The tests that don't specify "--debug" are expected to
# throw exceptions.  If --debug is on we'll get a stack
# trace, which is unpredictable and doesn't work well with
# expected.txt vs. out.txt comparisons.

function check_rejected {
  dx --dump --width=100 --strict $1
}

function check_accepted {
  dx --debug --dump --width=100 $1
}

# Bad magic (throws an expection)
check_rejected class-bad-magic.txt

# Too small (throws an exception)
check_rejected class-version-44.0.txt
check_rejected class-version-44.65535.txt

# Just right
check_accepted class-version-45.0.txt
check_accepted class-version-45.65535.txt
check_accepted class-version-48.0.txt
check_accepted class-version-48.65535.txt
check_accepted class-version-49.0.txt
check_accepted class-version-49.1.txt
check_accepted class-version-49.65535.txt
check_accepted class-version-50.0.txt
check_accepted class-version-50.1.txt
check_accepted class-version-50.65535.txt
check_accepted class-version-51.0.txt
check_accepted class-version-51.65535.txt
check_accepted class-version-52.0.txt
check_accepted class-version-52.1.txt
check_accepted class-version-52.65535.txt
check_accepted class-version-53.0.txt

# Too big (throws an exception)
check_rejected class-version-53.1.txt
check_rejected class-version-53.65535.txt
check_rejected class-version-54.0.txt

# Show that we can dump the access flags even when they
# don't make any sense.
check_accepted small-class.txt
