#!/bin/bash
#
# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function follow_links() {
  file="$1"
  while [ -h "$file" ]; do
    # On Mac OS, readlink -f doesn't work.
    file="$(readlink "$file")"
  done
  echo "$file"
}

PROG_NAME="$(follow_links "$BASH_SOURCE")"
PROG_DIR="$(cd "${PROG_NAME%/*}" ; pwd -P)"
ANDROID_BUILD_TOP="$(cd "${PROG_DIR}/../../../../" ; pwd -P)/"
ANDROID_DATA=$PWD/android-data$$

mkdir -p $ANDROID_DATA/dalvik-cache
ANDROID_PRINTF_LOG=tag \
ANDROID_LOG_TAGS="" \
ANDROID_DATA=$ANDROID_DATA \
ANDROID_ROOT=$ANDROID_BUILD_TOP/out/host/linux-x86 \
LD_LIBRARY_PATH=$ANDROID_BUILD_TOP/out/host/linux-x86/lib \
$ANDROID_BUILD_TOP/out/host/linux-x86/bin/dalvikvm \
-Xbootclasspath\
:$ANDROID_BUILD_TOP/out/host/linux-x86/framework/core-hostdex.jar\
:$ANDROID_BUILD_TOP/out/host/linux-x86/framework/conscrypt-hostdex.jar\
:$ANDROID_BUILD_TOP/out/host/linux-x86/framework/okhttp-hostdex.jar\
:$ANDROID_BUILD_TOP/out/host/linux-x86/framework/bouncycastle-hostdex.jar\
:$ANDROID_BUILD_TOP/out/host/linux-x86/framework/apache-xml-hostdex.jar \
$*
EXIT_STATUS=$?
rm -rf $ANDROID_DATA
exit $EXIT_STATUS
