#!/bin/bash
#
# Copyright (C) 2017 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

jar xf invokecustom.jar
(
  CLASSES=(invokecustom/Super.class invokecustom/InvokeCustom*.class)
  for CLASS in "${CLASSES[@]}"; do
    dx --min-sdk-version=26 --dex --output="${CLASS/%.class/.dex}" "${CLASS}" 2>&1
  done
)
java -cp $(dirname $(which dx))/../framework/dx.jar com.android.dx.merge.DexMerger \
  out.dex invokecustom/*.dex >& /dev/null
dexdump2 -d out.dex
