#!/bin/bash
#
# Copyright (C) 2017 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

function oneop()
{
    jasmin -d . op_"$1".j
}

oneop dup
oneop dup_x1_case1
oneop dup_x1_case2
oneop dup_x2_case1
oneop dup_x2_case2
oneop dup_x2_case3
oneop dup2
oneop dup2_x1_case1
oneop dup2_x1_case2
oneop dup2_x1_case3
oneop dup2_x2_case1
oneop dup2_x2_case2
oneop dup2_x2_case3
oneop pop
oneop pop2
oneop swap_case1
oneop swap_case2
