#!/bin/bash
#
# Copyright (C) 2017 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

JAVAC_SOURCE=1.6
JAVAC_TARGET=1.6

${JAVAC} -source ${JAVAC_SOURCE} -target ${JAVAC_TARGET} `find com -name "*.java"`
mkdir classes
${JAVAC} -source ${JAVAC_SOURCE} -target ${JAVAC_TARGET} -d classes `find testdata -name '*.java'`
