#!/bin/bash
#
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# m core-tests junit caliper snod && adb reboot bootloader && fastboot flashall && adb wait-for-device
# mmm dalvik/libcore/tools/runner

android_root=`dirname $0`/../../../..
cd ${android_root}

classpath=${android_root}/out/host/linux-x86/framework/dalvik_runner.jar
exec java -cp $classpath vogar.Vogar "$@"

