/*
 * Copyright (C) 2012 The Pennsylvania State University
 * Systems and Internet Infrastructure Security Laboratory
 *
 * Author: Damien Octeau <octeau@cse.psu.edu>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 */

/**
 * java_opcode_jasmin.h
 *
 * A list of Java opcodes in string format.
 */

#ifndef TYDE_JAVA_OPCODE_JASMIN_H
#define TYDE_JAVA_OPCODE_JASMIN_H

typedef const char* JavaOpCode;

const JavaOpCode
  NOP = "  nop",
  ACONST_NULL = "  aconst_null",
  ICONST_M1 = "  iconst_m1",
  ICONST_0 = "  iconst_0",
  ICONST_1 = "  iconst_1",
  ICONST_2 = "  iconst_2",
  ICONST_3 = "  iconst_3",
  ICONST_4 = "  iconst_4",
  ICONST_5 = "  iconst_5",
  LCONST_0 = "  lconst_0",
  LCONST_1 = "  lconst_1",
  FCONST_0 = "  fconst_0",
  FCONST_1 = "  fconst_1",
  FCONST_2 = "  fconst_2",
  DCONST_0 = "  dconst_0",
  DCONST_1 = "  dconst_1",
  BIPUSH = "  bipush",
  SIPUSH = "  sipush",
  LDC = "  ldc",
  LDC_W = "  ldc_w",
  LDC2_W = "  ldc2_w",
  ILOAD = "  iload",
  LLOAD = "  lload",
  FLOAD = "  fload",
  DLOAD = "  dload",
  ALOAD = "  aload",
  ILOAD_0 = "  iload_0",
  ILOAD_1 = "  iload_1",
  ILOAD_2 = "  iload_2",
  ILOAD_3 = "  iload_3",
  LLOAD_0 = "  lload_0",
  LLOAD_1 = "  lload_1",
  LLOAD_2 = "  lload_2",
  LLOAD_3 = "  lload_3",
  FLOAD_0 = "  fload_0",
  FLOAD_1 = "  fload_1",
  FLOAD_2 = "  fload_2",
  FLOAD_3 = "  fload_3",
  DLOAD_0 = "  dload_0",
  DLOAD_1 = "  dload_1",
  DLOAD_2 = "  dload_2",
  DLOAD_3 = "  dload_3",
  ALOAD_0 = "  aload_0",
  ALOAD_1 = "  aload_1",
  ALOAD_2 = "  aload_2",
  ALOAD_3 = "  aload_3",
  IALOAD = "  iaload",
  LALOAD = "  laload",
  FALOAD = "  faload",
  DALOAD = "  daload",
  AALOAD = "  aaload",
  BALOAD = "  baload",
  CALOAD = "  caload",
  SALOAD = "  saload",
  ISTORE = "  istore",
  LSTORE = "  lstore",
  FSTORE = "  fstore",
  DSTORE = "  dstore",
  ASTORE = "  astore",
  ISTORE_0 = "  istore_0",
  ISTORE_1 = "  istore_1",
  ISTORE_2 = "  istore_2",
  ISTORE_3 = "  istore_3",
  LSTORE_0 = "  lstore_0",
  LSTORE_1 = "  lstore_1",
  LSTORE_2 = "  lstore_2",
  LSTORE_3 = "  lstore_3",
  FSTORE_0 = "  fstore_0",
  FSTORE_1 = "  fstore_1",
  FSTORE_2 = "  fstore_2",
  FSTORE_3 = "  fstore_3",
  DSTORE_0 = "  dstore_0",
  DSTORE_1 = "  dstore_1",
  DSTORE_2 = "  dstore_2",
  DSTORE_3 = "  dstore_3",
  ASTORE_0 = "  astore_0",
  ASTORE_1 = "  astore_1",
  ASTORE_2 = "  astore_2",
  ASTORE_3 = "  astore_3",
  IASTORE = "  iastore",
  LASTORE = "  lastore",
  FASTORE = "  fastore",
  DASTORE = "  dastore",
  AASTORE = "  aastore",
  BASTORE = "  bastore",
  CASTORE = "  castore",
  SASTORE = "  sastore",
  POP = "  pop",
  POP2 = "  pop2",
  DUP = "  dup",
  DUP_X1 = "  dup_x1",
  DUP_X2 = "  dup_x2",
  DUP2 = "  dup2",
  DUP2_X1 = "  dup2_x1",
  DUP2_X2 = "  dup2_x2",
  SWAP = "  swap",
  IADD = "  iadd",
  LADD = "  ladd",
  FADD = "  fadd",
  DADD = "  dadd",
  ISUB = "  isub",
  LSUB = "  lsub",
  FSUB = "  fsub",
  DSUB = "  dsub",
  IMUL = "  imul",
  LMUL = "  lmul",
  FMUL = "  fmul",
  DMUL = "  dmul",
  IDIV = "  idiv",
  LDIV = "  ldiv",
  FDIV = "  fdiv",
  DDIV = "  ddiv",
  IREM = "  irem",
  LREM = "  lrem",
  FREM = "  frem",
  DREM = "  drem",
  INEG = "  ineg",
  LNEG = "  lneg",
  FNEG = "  fneg",
  DNEG = "  dneg",
  ISHL = "  ishl",
  LSHL = "  lshl",
  ISHR = "  ishr",
  LSHR = "  lshr",
  IUSHR = "  iushr",
  LUSHR = "  lushr",
  IAND = "  iand",
  LAND = "  land",
  IOR = "  ior",
  LOR = "  lor",
  IXOR = "  ixor",
  LXOR = "  lxor",
  IINC = "  iinc",
  I2L = "  i2l",
  I2F = "  i2f",
  I2D = "  i2d",
  L2I = "  l2i",
  L2F = "  l2f",
  L2D = "  l2d",
  F2I = "  f2i",
  F2L = "  f2l",
  F2D = "  f2d",
  D2I = "  d2i",
  D2L = "  d2l",
  D2F = "  d2f",
  I2B = "  int2byte",
  I2C = "  int2char",
  I2S = "  int2short",
  LCMP = "  lcmp",
  FCMPL = "  fcmpl",
  FCMPG = "  fcmpg",
  DCMPL = "  dcmpl",
  DCMPG = "  dcmpg",
  IFEQ = "  ifeq",
  IFNE = "  ifne",
  IFLT = "  iflt",
  IFGE = "  ifge",
  IFGT = "  ifgt",
  IFLE = "  ifle",
  IF_ICMPEQ = "  if_icmpeq",
  IF_ICMPNE = "  if_icmpne",
  IF_ICMPLT = "  if_icmplt",
  IF_ICMPGE = "  if_icmpge",
  IF_ICMPGT = "  if_icmpgt",
  IF_ICMPLE = "  if_icmple",
  IF_ACMPEQ = "  if_acmpeq",
  IF_ACMPNE = "  if_acmpne",
  GOTO = "  goto",
  JSR = "  jsr",
  RET = "  ret",
  TABLESWITCH = "  tableswitch",
  LOOKUPSWITCH = "  lookupswitch",
  IRETURN = "  ireturn",
  LRETURN = "  lreturn",
  FRETURN = "  freturn",
  DRETURN = "  dreturn",
  ARETURN = "  areturn",
  RETURN = "  return",
  GETSTATIC = "  getstatic",
  PUTSTATIC = "  putstatic",
  GETFIELD = "  getfield",
  PUTFIELD = "  putfield",
  INVOKEVIRTUAL = "  invokevirtual",
  INVOKESPECIAL = "  invokespecial",
  INVOKESTATIC = "  invokestatic",
  INVOKEINTERFACE = "  invokeinterface",
  UNUSED_BA = "  unused_ba",
  NEW = "  new",
  NEWARRAY = "  newarray",
  ANEWARRAY = "  anewarray",
  ARRAYLENGTH = "  arraylength",
  ATHROW = "  athrow",
  CHECKCAST = "  checkcast",
  INSTANCEOF = "  instanceof",
  MONITORENTER = "  monitorenter",
  MONITOREXIT = "  monitorexit",
  WIDE = "  wide",
  MULTIANEWARRAY = "  multianewarray",
  IFNULL = "  ifnull",
  IFNONNULL = "  ifnonnull",
  GOTO_W = "  goto_w",
  JSR_W = "  jsr_w",
  UNUSED_CA = "  unused_ca",
  UNUSED_FF = "  unused_ff";


#endif /* TYDE_JAVA_OPCODE_JASMIN_H */
