/*
 * Copyright (C) 2007 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tests.api.javax.net.ssl;

import junit.framework.Test;
import junit.framework.TestSuite;

/**
 * This is autogenerated source file. Includes tests for package tests.api.javax.net.ssl;
 */

public class AllTests {

    public static void main(String[] args) {
        junit.textui.TestRunner.run(AllTests.suite());
    }

    public static Test suite() {
        TestSuite suite = new TestSuite("All tests for package tests.api.javax.net.ssl;");
        // $JUnit-BEGIN$

        suite.addTestSuite(CertPathTrustManagerParametersTest.class);
        suite.addTestSuite(HandshakeCompletedEventTest.class);
        suite.addTestSuite(HttpsURLConnectionTest.class);
        suite.addTestSuite(KeyManagerFactory1Test.class);
        suite.addTestSuite(KeyManagerFactory2Test.class);
        suite.addTestSuite(KeyManagerFactorySpiTest.class);
        suite.addTestSuite(SSLContext1Test.class);
        suite.addTestSuite(SSLContext2Test.class);
        suite.addTestSuite(SSLContextSpiTest.class);
        suite.addTestSuite(SSLEngineResultTest.class);
        suite.addTestSuite(SSLEngineTest.class);
        suite.addTestSuite(SSLPermissionTest.class);
        suite.addTestSuite(SSLServerSocketFactoryTest.class);
        suite.addTestSuite(SSLSessionBindingEventTest.class);
        suite.addTestSuite(SSLSocketFactoryTest.class);
        suite.addTestSuite(TrustManagerFactory1Test.class);
        suite.addTestSuite(TrustManagerFactory2Test.class);
        suite.addTestSuite(TrustManagerFactorySpiTest.class);
        suite.addTestSuite(X509ExtendedKeyManagerTest.class);

        // $JUnit-END$
        return suite;
    }
}
