/*
 * Copyright (C) 2007 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tests.java.sql;

import junit.framework.Test;
import junit.framework.TestSuite;

/**
 * This is autogenerated source file. Includes tests for package tests.java.sql;
 */

public class AllTests {

    public static void main(String[] args) {
        junit.textui.TestRunner.run(AllTests.suite());
    }

    public static Test suite() {
        TestSuite suite = new TestSuite("All tests for package tests.java.sql;");
        // $JUnit-BEGIN$

        suite.addTest(DatabaseMetaDataTest.suite());
        suite.addTest(MultiThreadAccessTest.suite());
        suite.addTest(StressTest.suite());
        suite.addTest(UpdateFunctionalityTest.suite());
        suite.addTest(SelectFunctionalityTest.suite());
        suite.addTest(UpdateFunctionalityTest2.suite());
        suite.addTest(DeleteFunctionalityTest.suite());
        suite.addTest(InsertFunctionalityTest.suite());

        // $JUnit-END$
        return suite;
    }
}
